name: Go CI

on:
  release:
    types:
      - created  
      - edited    
      - deleted    
      - prereleased

jobs:
  address-files:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List root directory
        run: ls

      - name: List cmd directory
        run: |
          cd cmd
          ls

      - name: List KV-Toolbox directory
        run: |
          cd cmd/KV-Toolbox
          ls

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install Fyne CLI
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          echo "C:\Users\runneradmin\go\bin" >> $env:GITHUB_PATH
          fyne version

      - name: Create output directory
        run: mkdir -p cmd/KV-Toolbox/output

      - name: Build for Windows
        run: |
          cd cmd/KV-Toolbox
          fyne package -os windows -icon icon.png -name ManageDB
          mv ManageDB.exe output

      - name: List output directory
        run: dir cmd\KV-Toolbox\output

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-windows
          path: cmd/KV-Toolbox/output

  upload-release-asset:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: output-windows
          path: output/windows

      - name: List all outputs
        run: |
          echo "Windows Output:"
          ls -lh output/windows

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.EDIT_RELEASE_KV_T }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: output/windows/ManageDB.exe
          asset_name: ManageDB.exe
          asset_content_type: application/octet-stream
