name: Go CI

on:
  push:
    branches:
      - Create-pipeline
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install dependencies
        run: go mod tidy

      - name : install pckage fyne
        run: go get fyne.io/fyne/v2

      - name : install pckage fyne2
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name : set address in system
        run: export GOPATH=$HOME/go

      - name : set address in system2
        run: export PATH=$PATH:$GOPATH/bin

      - name : list
        run : ls

      - name : type system
        run : uname -a
        
      - name : go to cmd
        run : |
          cd cmd
          cd KV-Toolbox
          mkdir output
          fyne package -os darwin -icon icon.png -name ManageDB
          mv ManageDB.app output
          ls

          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
            name: build-artifacts
            path: cmd/KV-Toolbox/output/

      - name : go to cmd
        run : |
              cd cmd
              cd KV-Toolbox
              ls
              cd output
              ls

  send-release:
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts


      - name : clone github
        run : git clone https://Mohsen20031203:PIPELINE_TOKEN_MS@github.com/Mohsen20031203/KV-Toolbox.git

      - name : install CLI
        run : sudo apt-get install gh


      - name: Create Release
        env:
          token: ${{ secrets.PIPELINE_TOKEN_MS }}
        run: |
          gh release create v1.3.0 ManageDB.app --title " 1.3.0" --notes ""







        

